### ISSUE TITLE
Replace string in summary or description

### ISSUE THREAD

**Issue by alanmilinovic** [darkphnx/ical-filter-proxy#45]
Is it possible to add a feature that can replace certain string in summary or description fields?

Like this:
```
replace:
      - field: summary
        old_str: "some old summary"
        new_str: "some new summary"
      - field: description
        old_str: "some old description"
        new_str: "some new description"
```

Thank you very much.
